name: Publish Website to CPanel

on:
  
  push:
    branches: 
      - main

jobs:
  deploy:
    environment:
      name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: actions/deploy-pages@v1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          
